loader_params:
    train_bs: 64
    val_bs: 64
    csv_root: meta_files/meta_data_train_Nah&Lung.csv
    csv_HaN_OAR_priority_root: meta_files/HaN_OAR_update.csv
    csv_LUNG_OAR_priority_root: meta_files/LUNG_OAR_update.csv
    scale_dose_dict: meta_files/PTV_DICT.json
    pat_obj_dict: meta_files/Pat_Obj_DICT.json
    num_workers: 16
    train_root: Dataset_256_DoseDINO/Train
    valid_root: Dataset_256_DoseDINO/Valid
    test_root: Dataset_256_DoseDINO/Test
    with_aug: false
    down_HU: -1000
    up_HU: 1000
    denom_norm_HU: 500
    in_size: [96, 256, 256]
    out_size: [96, 256, 256]
    CatStructures: false
    dose_div_factor: 10

model_params:
    input_channels: 6
    out_channels: 1
    checkpoint_path: dino_unetr/model.pth
    rk4_steps: 4

strategy: default
lr: 0.0001
weight_decay: 0.0001
num_epochs: 200
scale_out: 7.5
scale_loss: 4
save_model_root: trained_models/dosedino
