

loader_params: 

    'train_bs': 1
    'val_bs': 1
    'csv_root': 'meta_files/meta_data_train_Nah&Lung.csv'
    'csv_HaN_OAR_priority_root': 'meta_files/HaN_OAR_update.csv'
    'csv_LUNG_OAR_priority_root': 'meta_files/LUNG_OAR_update.csv'
    'scale_dose_dict': 'meta_files/PTV_DICT.json'
    'pat_obj_dict': 'meta_files/Pat_Obj_DICT.json'
    'num_workers': 0

    'down_HU': -1000
    'up_HU': 1000
    'denom_norm_HU': 500

    'in_size': [96, 256, 256]
    'out_size': [96, 256, 256]

    'CatStructures': False
    'dose_div_factor': 10 
    
strategy: 'default' # Options: lora, llrd, frozen, adapter, default
layout: False # True for MED_DINO_UNETR_layout, False for MED_DINO_UNETR
use_nmODE: False # True for MED_DINO_UNETR_nmODE, False for MED_DINO_UNETR

model_params:
    input_channels: 5
    out_channels: 1

lr: 0.0001
num_epochs: 120

act_sig: False
scale_out: 7.5


model_from_lightning: True
save_model_path: trained_models\trained_model_default_256_meddino_changechannel_nodistance_nah&lung\dinounetr-best-val-epoch=25-val_loss=0.2470.ckpt
save_pred_path: results\result_default_256_meddino_changechannel_nodistance_nah&lung
